name: Airtable

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run airtable script to fetch news and team members
        env:
          AIRTABLE_NEWS_BASE_KEY: ${{ secrets.AIRTABLE_NEWS_BASE_KEY }}
          AIRTABLE_TEAM_BASE_KEY: ${{ secrets.AIRTABLE_TEAM_BASE_KEY }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        working-directory: scripts
        run: |
          pip3 install airtable-python-wrapper > /dev/null
          chmod +x airtable-auto.py
          ./airtable-auto.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: "auto-add from Airtable"
          title: "Airtable GitHub action -- Update News and Team"
          body: "Updates to News and Team Members from Airtable"
