# copied directly from Colby's previous work:  https://github.com/covid19risk/legacy_website/blob/12ebd1324c1c03bdab90c9522ecabbf6f9e53014/.github/workflows/airtable.yaml

name: Airtable

on:
  schedule: 
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run airtable script
        env:
          AIRTABLE_BASE_KEY: ${{ secrets.AIRTABLE_BASE_KEY }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }} 
        working-directory: scripts
        run: |
          pip3 install airtable-python-wrapper
          chmod +x airtable-auto.py
          ./airtable-auto.py
          
      - name: Create Pull Request
        uses: colbymorrison/create-pull-request@v2
        with:
          commit-message: "auto-add new news"
          title: "Airtable GitHub action -- Update News"
          body: "New News from Airtable"
