name: Prettier Code Formatting

on:
  pull_request:
    branches: [master]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Run Prettier
        uses: creyD/prettier_action@v3.0
        with:
          prettier_options: --write **/*.{js,vue,md,html}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
