name: Prettier Code Formatting

on:
  pull_request:
    branches: [master]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prettier Action
        uses: creyD/prettier_action@v3.0
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,vue,md,html}
